env:
  global:
    - EXTENSION_ID=wishitch@dbuteau.github.com  
    - WEB_EXT_SOURCE_DIR=./xpi/

sudo: false
language: node_js

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: lint
      node_js:
        - '10'
      before_script:
        - unset WEB_EXT_API_KEY
        - unset WEB_EXT_API_SECRET
      script: npm run test

    - stage: deploy
      name: create release file on github
      node_js:
        - '10'
      api_key: $GH_TOKEN
      WEB_EXT_CHANNEL: unlisted
      before_deploy:
        - npm run build
        - npm run sign
      provider: releases
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file: "*.xpi"
      draft: true
      on:
        branch: master

    - stage: deploy
      name: release on AMO
      node_js:
        - '10'
      WEB_EXT_CHANNEL: listed
      provider: script
      skip_cleanup: true
      script: "npm run release"
      on:
        tags: true

