env:
  global:
    - EXTENSION_ID=wishitch@dbuteau.github.com  
    - WEB_EXT_SOURCE_DIR=./xpi/

sudo: false
language: node_js
node_js:
  - node

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: lint xpi
      before_script:
        - unset WEB_EXT_API_KEY
        - unset WEB_EXT_API_SECRET
      script: npm run test

    - stage: deploy
      name: release-xpi on github
      provider: releases
      before_script:
        - CHANGED_FILES=`git diff --name-only master ${TRAVIS_COMMIT}`
        - if echo ${CHANGED_FILES} | grep -v -e "xpi\/"; then travis_terminate 0; fi
        - 'sed -i s/"version": "(.*)",/"version": "\1-$TRAVIS_BUILD_NUMBER-beta",/ ./xpi/manifest.json'
        - web-ext sign --channel=unlisted -a build/
      api_key: $GH_TOKEN
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file: "build/*.xpi"
      draft: true
      on:
        branch: master

    - stage: deploy
      name: release-xpi on AMO
      provider: script
      skip_cleanup: true
      draft: false
      script: 
        - CHANGED_FILES=`git diff --name-only master ${TRAVIS_COMMIT}`
        - if echo ${CHANGED_FILES} | grep -v -e "xpi\/"; then travis_terminate 0; fi
        - 'sed -i s/"version": "(.*)",/"version": "$TRAVIS_TAG",/ ./xpi/manifest.json'
        - web-ext sign --channel=listed
      if: tag IS present

