version: '3'
services:
  wishitch:
    image: "dbuteau/wishitch:latest"
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      HOSTNAME: "['127.0.0.1','localhost']"
      ADMIN_LOGIN: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
    volumes:
	- 
